spring:
  profiles:
    active: local
  application:
    name: STOCK-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQLDialect