spring:
  profiles:
    active: local
  application:
    name: PRODUCT-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQLDialect

sonar:
  coverage:
    exclusions: "**/model/**"