apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapp
  template:
    metadata:
      labels:
        app: orderapp
    spec:
      containers:
        - name: orderapp
          image: yuzarsifkilic/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9093
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djdk.tls.client.protocols=TLSv1.2"
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: order-db-url
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "order-db"
            - name: SPRING_PROFILES_ACTIVE
              value: dev

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: orderapp
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093