name: Cart Service Pipeline

on:
  push:
    branches:
      - main
    paths:
      - cart-service/**
      - .github/workflows/cart-service-pipeline.yml

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Directories
        run: ls -la

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for mvnw
        run: chmod +x cart-service/mvnw

      - name: Extract Project Version
        id: extract_version
        run: |
          cd cart-service
          VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "::set-output name=version::$VERSION"

  build:
    name: Build Cart Service
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build with Maven
        run: |
          cd cart-service
          ./mvnw clean compile

  test:
    name: Test Cart Service
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Running Tests
        run: |
          cd cart-service
          ./mvnw clean test

  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [build, test, setup]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: cart-service
          file: cart-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cart-service:${{ needs.setup.outputs.version }}
            ${{ secrets.DOCKER_USERNAME }}/cart-service:latest